name: hip_quest
description: A Learning Platform.

publish_to: 'none'

version: 1.0.0+6

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  connectivity_plus: ^3.0.2
  mask_text_input_formatter: ^2.3.0
  onesignal_flutter: ^5.0.4
  get_it: ^7.2.0
  flutter_styled_toast: ^2.2.1
  shared_preferences: ^2.0.15
  dio: ^4.0.6
  provider: ^6.0.2
  cached_network_image: ^3.2.1
  image_picker: ^0.8.5+3
  adaptive_action_sheet: ^2.0.2
  cloud_firestore: ^4.3.1
  firebase_core: ^2.4.1
  firebase_messaging: ^14.2.1
  flutter_local_notifications: ^9.8.0+1
  avatar_view: ^1.0.1
  webview_flutter: ^2.0.4
  blurrycontainer: ^1.0.2
  flutter_html: ^3.0.0-alpha.6
  vimeo_video_player: ^0.0.4
  intl: ^0.18.1
  device_info_plus: ^8.0.0
  uuid: ^3.0.6
  firebase_crashlytics: ^3.0.11
  flutter_cached_pdfview: ^0.4.1
  http: ^0.13.5
  image_cropper: ^3.0.1
  firebase_database: ^10.1.0
  path_provider: ^2.1.1
  firebase_auth: ^4.14.1
  fluttertoast: ^8.2.4
  firebase_storage: ^11.5.2
  photo_view: ^0.14.0



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: sans
      fonts:
        - asset: assets/fonts/WorkSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/WorkSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/WorkSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/WorkSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/WorkSans-Light.ttf
          weight: 300
